# How many distinct terms are in the sequence generated by a^b for 2<=a<=100 and 2<=b<=100
def find_terms(a, b, distinct_terms):
    distinct_terms.append(pow(a, b))
    return sorted(set(distinct_terms)), len(set(distinct_terms))


def send_values(a, b):
    distinct_terms = []
    for i in range(a, b + 1):
        for j in range(a, b + 1):
            terms, count = find_terms(i, j, distinct_terms)
    return terms, count


term_list, count = send_values(2, 5)
print(count, term_list)
